[github]
# Register the app here: https://github.com/settings/applications/new
client_id = ""
client_secret = ""

[sqlalchemy]
database_url = "sqlite:///./quetz.sqlite"

[session]
secret = "ef689d49f2624347bd2c36d48bccd86004ef66593bf7c73605a64cc8d284c0e9"
https_only = false
